version: "3.9"

services:
  jcs-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jcs-backend
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=remote
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    networks:
      - jcs-network

networks:
  jcs-network: